# Generated by Django 3.0.9 on 2020-08-14 13:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_time', models.DateTimeField(auto_now=True, null=True, verbose_name='updated')),
                ('language', models.CharField(choices=[('en', 'English'), ('pt-BR', 'Portuguese'), ('es', 'Spanish')], max_length=10, verbose_name='Language')),
                ('label', models.CharField(max_length=255, verbose_name='Option')),
                ('group', models.SmallIntegerField(blank=True, verbose_name='Group')),
                ('filter_query', models.CharField(blank=True, max_length=125, verbose_name='Filter query')),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Option',
                'verbose_name_plural': 'Options',
            },
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_time', models.DateTimeField(auto_now=True, null=True, verbose_name='updated')),
                ('step_number', models.SmallIntegerField(default=1, null=True, verbose_name='Step')),
                ('language', models.CharField(choices=[('en', 'English'), ('pt-BR', 'Portuguese'), ('es', 'Spanish')], max_length=10, verbose_name='Language')),
                ('label', models.CharField(max_length=255, verbose_name='Label')),
                ('filter_name', models.CharField(blank=True, max_length=55, verbose_name='Filter name')),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Step',
                'verbose_name_plural': 'Steps',
            },
        ),
        migrations.CreateModel(
            name='Wizard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_time', models.DateTimeField(auto_now=True, null=True, verbose_name='updated')),
                ('name', models.CharField(max_length=125, verbose_name='Name')),
                ('code', models.SlugField(default='', editable=False, max_length=125, verbose_name='Code')),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Wizard',
                'verbose_name_plural': 'Wizards',
            },
        ),
        migrations.CreateModel(
            name='StepLocal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('pt-BR', 'Portuguese'), ('es', 'Spanish')], max_length=10, verbose_name='Language')),
                ('label', models.CharField(max_length=255, verbose_name='Label')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Step', verbose_name='Step')),
            ],
            options={
                'verbose_name': 'Translation',
                'verbose_name_plural': 'Translations',
            },
        ),
        migrations.AddField(
            model_name='step',
            name='wizard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.Wizard', verbose_name='Wizard'),
        ),
        migrations.CreateModel(
            name='OptionLocal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('pt-BR', 'Portuguese'), ('es', 'Spanish')], max_length=10, verbose_name='Language')),
                ('label', models.CharField(max_length=255, verbose_name='Label')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Option', verbose_name='Option')),
            ],
            options={
                'verbose_name': 'Translation',
                'verbose_name_plural': 'Translations',
            },
        ),
        migrations.AddField(
            model_name='option',
            name='step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.Step', verbose_name='Step'),
        ),
        migrations.AddField(
            model_name='option',
            name='updated_by',
            field=django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
